### ISSUE TITLE
[feature request] PCAPs download through Tulip frontend

### ISSUE THREAD

**Issue by erdnaxe** [OpenAttackDefenseTools/tulip#12]
Currently Tulip shows the path of the PCAP associated with a TCP flow.
It would be nice to change this to a hyperlink pointing to the PCAP, enabling other team members to download it for local analysis.

Should we allow the backend to access PCAPs path to serve it to other users?

**Comment by RickdeJager** [comment]
Solved in d96f928b60883fc5497397d17140edc331ea6dbe, which I'll merge to master soon
